<script setup lang="ts">
const auctions = ref<any>([]);
const { $shopApi: shopApi } = useNuxtApp();
const route = useRoute();
const currentFirm = ref<any>(null);

onMounted(() => {
  fetchAuctions();
});

const fetchAuctions = async () => {
  const firmToken = route.query.firmToken as string;
  // const { data: response } = await shopApi.get(`/api/get-auctions/${firmToken}`) as any;
  currentFirm.value =    {
    "id": 295,
    "name": "GENDERKA SP Z O O",
    "short_name": "GENDERKA SP Z O O",
    "symbol": "GENDERKA-BYDGOSZCZ",
    "delivery_warehouse": null,
    "email": "chabierski@genderka.pl",
    "secondary_email": null,
    "complaint_email": "",
    "nip": "5542772061",
    "account_number": null,
    "status": "ACTIVE",
    "phone": "523205016",
    "secondary_phone": null,
    "notices": null,
    "secondary_notices": "Nie przyjmuj\u0105 zam\u00f3wie\u0144 w tym momencie. Je\u015bli na Bia\u0142ystok to trzeba si\u0119 wtedy dopytywa\u0107 jaka cena. ",
    "created_at": "2019-01-25T11:22:28.000000Z",
    "updated_at": "2024-02-03T18:45:55.000000Z",
    "id_from_old_db": null,
    "firm_type": "PRODUCTION",
    "send_request_to_update_data": 0,
    "access_token": "oIxw8rDgVddNpmofiFV5Cz3tnHwnoFPFA3DSa5J5v7P4GAGTzZT8Arx5SrTy"
  }

  auctions.value = [
      {
        "id": 36,
        "end_of_auction": "2024-02-08",
        "date_of_delivery": "2024-02-16",
        "price": 50,
        "quality": 50,
        "chat_id": 10555,
        "confirmed": 1,
        "created_at": "2024-02-03T09:37:34.000000Z",
        "updated_at": "2024-02-03T09:43:02.000000Z",
        "editPricesLink": "https:\/\/admin.mega1000.pl\/auctions\/offer\/create\/6u9tSVsI301WCopC38RB9a1XaqooDiXrpO5kdAayCSKlRhrkHdvp5OJ8VXHN",
        "offers": [
          {
            "id": 86,
            "commercial_price_net": 45.6,
            "basic_price_net": 152,
            "calculated_price_net": 30.4,
            "aggregate_price_net": 0,
            "commercial_price_gross": 56.09,
            "basic_price_gross": 186.96,
            "calculated_price_gross": 37.39,
            "aggregate_price_gross": 0,
            "order_item_id": 248909,
            "chat_auction_id": 36,
            "firm_id": 736,
            "created_at": "2024-02-03T09:50:03.000000Z",
            "updated_at": "2024-02-03T09:50:03.000000Z",
            "send_notification": 0,
            "firm": {
              "id": 736,
              "name": "",
              "short_name": "",
              "symbol": "CWANIAK-SIANOWO",
              "delivery_warehouse": null,
              "email": "579qqq@o2.pl",
              "secondary_email": null,
              "complaint_email": "",
              "nip": "",
              "account_number": "",
              "status": "ACTIVE",
              "phone": "602256996",
              "secondary_phone": null,
              "notices": "M",
              "secondary_notices": null,
              "created_at": "2019-01-25T11:22:39.000000Z",
              "updated_at": "2024-02-03T18:46:00.000000Z",
              "id_from_old_db": null,
              "firm_type": "PRODUCTION",
              "send_request_to_update_data": 0,
              "access_token": "IrAblIzonC5RSIANiOaGCrzhPAUc4TMY4ca3szwbVGdAURtzfEjrpDXJth7f",
              "laravel_through_key": 736
            }
          },
          {
            "id": 87,
            "commercial_price_net": 57.6,
            "basic_price_net": 192,
            "calculated_price_net": 9.6,
            "aggregate_price_net": 0,
            "commercial_price_gross": 70.85,
            "basic_price_gross": 236.16,
            "calculated_price_gross": 11.81,
            "aggregate_price_gross": 0,
            "order_item_id": 248910,
            "chat_auction_id": 36,
            "firm_id": 736,
            "created_at": "2024-02-03T09:50:18.000000Z",
            "updated_at": "2024-02-03T09:50:18.000000Z",
            "send_notification": 0,
            "firm": {
              "id": 736,
              "name": "",
              "short_name": "",
              "symbol": "CWANIAK-SIANOWO",
              "delivery_warehouse": null,
              "email": "579qqq@o2.pl",
              "secondary_email": null,
              "complaint_email": "",
              "nip": "",
              "account_number": "",
              "status": "ACTIVE",
              "phone": "602256996",
              "secondary_phone": null,
              "notices": "M",
              "secondary_notices": null,
              "created_at": "2019-01-25T11:22:39.000000Z",
              "updated_at": "2024-02-03T18:46:00.000000Z",
              "id_from_old_db": null,
              "firm_type": "PRODUCTION",
              "send_request_to_update_data": 0,
              "access_token": "IrAblIzonC5RSIANiOaGCrzhPAUc4TMY4ca3szwbVGdAURtzfEjrpDXJth7f",
              "laravel_through_key": 736
            }
          },
          {
            "id": 88,
            "commercial_price_net": 45.6,
            "basic_price_net": 152,
            "calculated_price_net": 30.4,
            "aggregate_price_net": 0,
            "commercial_price_gross": 56.09,
            "basic_price_gross": 186.96,
            "calculated_price_gross": 37.39,
            "aggregate_price_gross": 0,
            "order_item_id": 248909,
            "chat_auction_id": 36,
            "firm_id": 736,
            "created_at": "2024-02-03T09:50:39.000000Z",
            "updated_at": "2024-02-03T09:50:39.000000Z",
            "send_notification": 0,
            "firm": {
              "id": 736,
              "name": "",
              "short_name": "",
              "symbol": "CWANIAK-SIANOWO",
              "delivery_warehouse": null,
              "email": "579qqq@o2.pl",
              "secondary_email": null,
              "complaint_email": "",
              "nip": "",
              "account_number": "",
              "status": "ACTIVE",
              "phone": "602256996",
              "secondary_phone": null,
              "notices": "M",
              "secondary_notices": null,
              "created_at": "2019-01-25T11:22:39.000000Z",
              "updated_at": "2024-02-03T18:46:00.000000Z",
              "id_from_old_db": null,
              "firm_type": "PRODUCTION",
              "send_request_to_update_data": 0,
              "access_token": "IrAblIzonC5RSIANiOaGCrzhPAUc4TMY4ca3szwbVGdAURtzfEjrpDXJth7f",
              "laravel_through_key": 736
            }
          },
          {
            "id": 89,
            "commercial_price_net": 57.62,
            "basic_price_net": 192.08,
            "calculated_price_net": 19.21,
            "aggregate_price_net": 57.62,
            "commercial_price_gross": 70.87,
            "basic_price_gross": 236.26,
            "calculated_price_gross": 23.63,
            "aggregate_price_gross": 70.87,
            "order_item_id": 248911,
            "chat_auction_id": 36,
            "firm_id": 736,
            "created_at": "2024-02-03T09:50:59.000000Z",
            "updated_at": "2024-02-03T09:50:59.000000Z",
            "send_notification": 1,
            "firm": {
              "id": 736,
              "name": "",
              "short_name": "",
              "symbol": "CWANIAK-SIANOWO",
              "delivery_warehouse": null,
              "email": "579qqq@o2.pl",
              "secondary_email": null,
              "complaint_email": "",
              "nip": "",
              "account_number": "",
              "status": "ACTIVE",
              "phone": "602256996",
              "secondary_phone": null,
              "notices": "M",
              "secondary_notices": null,
              "created_at": "2019-01-25T11:22:39.000000Z",
              "updated_at": "2024-02-03T18:46:00.000000Z",
              "id_from_old_db": null,
              "firm_type": "PRODUCTION",
              "send_request_to_update_data": 0,
              "access_token": "IrAblIzonC5RSIANiOaGCrzhPAUc4TMY4ca3szwbVGdAURtzfEjrpDXJth7f",
              "laravel_through_key": 736
            }
          },
          {
            "id": 90,
            "commercial_price_net": 57.62,
            "basic_price_net": 192.08,
            "calculated_price_net": 9.6,
            "aggregate_price_net": 57.62,
            "commercial_price_gross": 70.87,
            "basic_price_gross": 236.26,
            "calculated_price_gross": 11.81,
            "aggregate_price_gross": 70.87,
            "order_item_id": 248910,
            "chat_auction_id": 36,
            "firm_id": 736,
            "created_at": "2024-02-03T09:51:03.000000Z",
            "updated_at": "2024-02-03T09:51:03.000000Z",
            "send_notification": 0,
            "firm": {
              "id": 736,
              "name": "",
              "short_name": "",
              "symbol": "CWANIAK-SIANOWO",
              "delivery_warehouse": null,
              "email": "579qqq@o2.pl",
              "secondary_email": null,
              "complaint_email": "",
              "nip": "",
              "account_number": "",
              "status": "ACTIVE",
              "phone": "602256996",
              "secondary_phone": null,
              "notices": "M",
              "secondary_notices": null,
              "created_at": "2019-01-25T11:22:39.000000Z",
              "updated_at": "2024-02-03T18:46:00.000000Z",
              "id_from_old_db": null,
              "firm_type": "PRODUCTION",
              "send_request_to_update_data": 0,
              "access_token": "IrAblIzonC5RSIANiOaGCrzhPAUc4TMY4ca3szwbVGdAURtzfEjrpDXJth7f",
              "laravel_through_key": 736
            }
          },
          {
            "id": 91,
            "commercial_price_net": 46.16,
            "basic_price_net": 153.86,
            "calculated_price_net": 30.77,
            "aggregate_price_net": 46.16,
            "commercial_price_gross": 56.78,
            "basic_price_gross": 189.25,
            "calculated_price_gross": 37.85,
            "aggregate_price_gross": 56.78,
            "order_item_id": 248909,
            "chat_auction_id": 36,
            "firm_id": 728,
            "created_at": "2024-02-05T09:29:09.000000Z",
            "updated_at": "2024-02-05T09:29:09.000000Z",
            "send_notification": 0,
            "firm": {
              "id": 728,
              "name": "CENTRUM BUDOWLANE TOMBUD PLUS SP. Z O.O. OSIELSKO",
              "short_name": "",
              "symbol": "TOMBUD-OSIELSKO",
              "delivery_warehouse": null,
              "email": "biuro@tombudplus.pl",
              "secondary_email": null,
              "complaint_email": "",
              "nip": "",
              "account_number": "",
              "status": "ACTIVE",
              "phone": "523813833",
              "secondary_phone": null,
              "notices": "M",
              "secondary_notices": null,
              "created_at": "2019-01-25T11:22:39.000000Z",
              "updated_at": "2024-02-03T18:46:00.000000Z",
              "id_from_old_db": null,
              "firm_type": "PRODUCTION",
              "send_request_to_update_data": 0,
              "access_token": "uxqyRrnLCdaRepxh26LVnGrSWhZclSAHH6WIhYzVNY6AZlZTO4ple5cjPJA6",
              "laravel_through_key": 728
            }
          },
          {
            "id": 92,
            "commercial_price_net": 45.6,
            "basic_price_net": 152,
            "calculated_price_net": 30.4,
            "aggregate_price_net": 0,
            "commercial_price_gross": 56.09,
            "basic_price_gross": 186.96,
            "calculated_price_gross": 37.39,
            "aggregate_price_gross": 0,
            "order_item_id": 248909,
            "chat_auction_id": 36,
            "firm_id": 728,
            "created_at": "2024-02-05T09:30:21.000000Z",
            "updated_at": "2024-02-05T09:30:21.000000Z",
            "send_notification": 0,
            "firm": {
              "id": 728,
              "name": "CENTRUM BUDOWLANE TOMBUD PLUS SP. Z O.O. OSIELSKO",
              "short_name": "",
              "symbol": "TOMBUD-OSIELSKO",
              "delivery_warehouse": null,
              "email": "biuro@tombudplus.pl",
              "secondary_email": null,
              "complaint_email": "",
              "nip": "",
              "account_number": "",
              "status": "ACTIVE",
              "phone": "523813833",
              "secondary_phone": null,
              "notices": "M",
              "secondary_notices": null,
              "created_at": "2019-01-25T11:22:39.000000Z",
              "updated_at": "2024-02-03T18:46:00.000000Z",
              "id_from_old_db": null,
              "firm_type": "PRODUCTION",
              "send_request_to_update_data": 0,
              "access_token": "uxqyRrnLCdaRepxh26LVnGrSWhZclSAHH6WIhYzVNY6AZlZTO4ple5cjPJA6",
              "laravel_through_key": 728
            }
          },
          {
            "id": 93,
            "commercial_price_net": 55.5,
            "basic_price_net": 185,
            "calculated_price_net": 9.25,
            "aggregate_price_net": 0,
            "commercial_price_gross": 68.27,
            "basic_price_gross": 227.55,
            "calculated_price_gross": 11.38,
            "aggregate_price_gross": 0,
            "order_item_id": 248910,
            "chat_auction_id": 36,
            "firm_id": 728,
            "created_at": "2024-02-05T09:30:45.000000Z",
            "updated_at": "2024-02-05T09:30:45.000000Z",
            "send_notification": 0,
            "firm": {
              "id": 728,
              "name": "CENTRUM BUDOWLANE TOMBUD PLUS SP. Z O.O. OSIELSKO",
              "short_name": "",
              "symbol": "TOMBUD-OSIELSKO",
              "delivery_warehouse": null,
              "email": "biuro@tombudplus.pl",
              "secondary_email": null,
              "complaint_email": "",
              "nip": "",
              "account_number": "",
              "status": "ACTIVE",
              "phone": "523813833",
              "secondary_phone": null,
              "notices": "M",
              "secondary_notices": null,
              "created_at": "2019-01-25T11:22:39.000000Z",
              "updated_at": "2024-02-03T18:46:00.000000Z",
              "id_from_old_db": null,
              "firm_type": "PRODUCTION",
              "send_request_to_update_data": 0,
              "access_token": "uxqyRrnLCdaRepxh26LVnGrSWhZclSAHH6WIhYzVNY6AZlZTO4ple5cjPJA6",
              "laravel_through_key": 728
            }
          },
          {
            "id": 94,
            "commercial_price_net": 55.5,
            "basic_price_net": 185,
            "calculated_price_net": 18.5,
            "aggregate_price_net": 0,
            "commercial_price_gross": 68.27,
            "basic_price_gross": 227.55,
            "calculated_price_gross": 22.75,
            "aggregate_price_gross": 0,
            "order_item_id": 248911,
            "chat_auction_id": 36,
            "firm_id": 728,
            "created_at": "2024-02-05T09:31:15.000000Z",
            "updated_at": "2024-02-05T09:31:15.000000Z",
            "send_notification": 0,
            "firm": {
              "id": 728,
              "name": "CENTRUM BUDOWLANE TOMBUD PLUS SP. Z O.O. OSIELSKO",
              "short_name": "",
              "symbol": "TOMBUD-OSIELSKO",
              "delivery_warehouse": null,
              "email": "biuro@tombudplus.pl",
              "secondary_email": null,
              "complaint_email": "",
              "nip": "",
              "account_number": "",
              "status": "ACTIVE",
              "phone": "523813833",
              "secondary_phone": null,
              "notices": "M",
              "secondary_notices": null,
              "created_at": "2019-01-25T11:22:39.000000Z",
              "updated_at": "2024-02-03T18:46:00.000000Z",
              "id_from_old_db": null,
              "firm_type": "PRODUCTION",
              "send_request_to_update_data": 0,
              "access_token": "uxqyRrnLCdaRepxh26LVnGrSWhZclSAHH6WIhYzVNY6AZlZTO4ple5cjPJA6",
              "laravel_through_key": 728
            }
          },
          {
            "id": 95,
            "commercial_price_net": 55.2,
            "basic_price_net": 184,
            "calculated_price_net": 9.2,
            "aggregate_price_net": 0,
            "commercial_price_gross": 67.9,
            "basic_price_gross": 226.32,
            "calculated_price_gross": 11.32,
            "aggregate_price_gross": 0,
            "order_item_id": 248910,
            "chat_auction_id": 36,
            "firm_id": 736,
            "created_at": "2024-02-05T12:11:04.000000Z",
            "updated_at": "2024-02-05T12:11:04.000000Z",
            "send_notification": 0,
            "firm": {
              "id": 736,
              "name": "",
              "short_name": "",
              "symbol": "CWANIAK-SIANOWO",
              "delivery_warehouse": null,
              "email": "579qqq@o2.pl",
              "secondary_email": null,
              "complaint_email": "",
              "nip": "",
              "account_number": "",
              "status": "ACTIVE",
              "phone": "602256996",
              "secondary_phone": null,
              "notices": "M",
              "secondary_notices": null,
              "created_at": "2019-01-25T11:22:39.000000Z",
              "updated_at": "2024-02-03T18:46:00.000000Z",
              "id_from_old_db": null,
              "firm_type": "PRODUCTION",
              "send_request_to_update_data": 0,
              "access_token": "IrAblIzonC5RSIANiOaGCrzhPAUc4TMY4ca3szwbVGdAURtzfEjrpDXJth7f",
              "laravel_through_key": 736
            }
          },
          {
            "id": 96,
            "commercial_price_net": 55.2,
            "basic_price_net": 184,
            "calculated_price_net": 18.4,
            "aggregate_price_net": 0,
            "commercial_price_gross": 67.9,
            "basic_price_gross": 226.32,
            "calculated_price_gross": 22.63,
            "aggregate_price_gross": 0,
            "order_item_id": 248911,
            "chat_auction_id": 36,
            "firm_id": 736,
            "created_at": "2024-02-05T12:11:17.000000Z",
            "updated_at": "2024-02-05T12:11:17.000000Z",
            "send_notification": 1,
            "firm": {
              "id": 736,
              "name": "",
              "short_name": "",
              "symbol": "CWANIAK-SIANOWO",
              "delivery_warehouse": null,
              "email": "579qqq@o2.pl",
              "secondary_email": null,
              "complaint_email": "",
              "nip": "",
              "account_number": "",
              "status": "ACTIVE",
              "phone": "602256996",
              "secondary_phone": null,
              "notices": "M",
              "secondary_notices": null,
              "created_at": "2019-01-25T11:22:39.000000Z",
              "updated_at": "2024-02-03T18:46:00.000000Z",
              "id_from_old_db": null,
              "firm_type": "PRODUCTION",
              "send_request_to_update_data": 0,
              "access_token": "IrAblIzonC5RSIANiOaGCrzhPAUc4TMY4ca3szwbVGdAURtzfEjrpDXJth7f",
              "laravel_through_key": 736
            }
          }
        ],
        "chat": {
          "id": 10555,
          "created_at": "2024-02-02T11:31:31.000000Z",
          "updated_at": "2024-02-03T09:42:25.000000Z",
          "product_id": null,
          "order_id": 85020,
          "need_intervention": 0,
          "user_id": 12,
          "complaint_form": "",
          "questions_tree": "",
          "order": {
            "id": 85020,
            "id_from_front_db": null,
            "customer_id": 56326,
            "status_id": 3,
            "firm_source_id": null,
            "last_status_update_date": null,
            "total_price": "0.00",
            "weight": "0.00",
            "shipment_price_for_client": "0.00",
            "shipment_price_for_us": null,
            "customer_notices": null,
            "cash_on_delivery_amount": null,
            "allegro_transaction_id": null,
            "employee_id": 50,
            "created_at": "2024-02-02T11:28:32.000000Z",
            "updated_at": "2024-02-03T09:43:02.000000Z",
            "warehouse_id": null,
            "additional_service_cost": null,
            "invoice_warehouse_file": null,
            "document_number": null,
            "consultant_earning": null,
            "warehouse_cost": null,
            "printed": "",
            "correction_description": null,
            "correction_amount": null,
            "packing_warehouse_cost": null,
            "rating": null,
            "rating_message": null,
            "shipping_abroad": 0,
            "proposed_payment": null,
            "additional_cash_on_delivery_cost": null,
            "shipment_date": null,
            "shipment_start_days_variation": null,
            "consultant_notices": null,
            "remainder_date": null,
            "invoice_number": null,
            "additional_info": null,
            "print_order": 0,
            "consultant_notice": null,
            "consultant_value": null,
            "warehouse_notice": null,
            "warehouse_value": null,
            "production_date": null,
            "master_order_id": null,
            "spedition_comment": "",
            "token": "PaOEWdOdO8PwlbQ73FrYujdf0n2COAlo",
            "payment_deadline": null,
            "sello_id": null,
            "initial_sending_date_client": null,
            "initial_sending_date_consultant": null,
            "initial_sending_date_magazine": null,
            "confirmed_sending_date_consultant": null,
            "initial_pickup_date_client": null,
            "confirmed_pickup_date_client": null,
            "confirmed_pickup_date_consultant": null,
            "initial_delivery_date_consultant": null,
            "confirmed_delivery_date": null,
            "proforma_filename": "i5ixIDLXRVh5d30HBh6CD0p1ALfhLUavsgL8b60A.pdf",
            "financial_comment": "",
            "return_payment_id": "",
            "to_refund": null,
            "refunded": null,
            "refund_id": null,
            "allegro_form_id": null,
            "allegro_deposit_value": null,
            "allegro_operation_date": null,
            "allegro_additional_service": null,
            "payment_channel": null,
            "labels_log": "\nDodano etykiet\u0119id:  2024-02-02 12:28:35 przez u\u017ctkownika: \nDodano etykiet\u0119id: 39 2024-02-02 12:28:38 przez u\u017ctkownika: \nDodano etykiet\u0119id: 39 2024-02-02 12:28:43 przez u\u017ctkownika: \nDodano etykiet\u0119id: 39 2024-02-02 12:28:47 przez u\u017ctkownika: \nDodano etykiet\u0119id: 39 2024-02-02 12:28:50 przez u\u017ctkownika: \nDodano etykiet\u0119id: 95 2024-02-02 12:28:50 przez u\u017ctkownika: \nDodano etykiet\u0119id: 39 2024-02-02 12:28:53 przez u\u017ctkownika: \nDodano etykiet\u0119id: 224 2024-02-02 12:36:53 przez u\u017ctkownika: 001\nDodano etykiet\u0119id: 58 2024-02-02 12:44:17 przez u\u017ctkownika: \nDodano etykiet\u0119id: 224 2024-02-02 12:44:36 przez u\u017ctkownika: 001\nDodano etykiet\u0119id: 224 2024-02-02 12:50:14 przez u\u017ctkownika: 001\nDodano etykiet\u0119id: 224 2024-02-03 08:54:07 przez u\u017ctkownika: 001\nDodano etykiet\u0119id: 58 2024-02-03 10:37:37 przez u\u017ctkownika: \nDodano etykiet\u0119id: 224 2024-02-03 10:43:02 przez u\u017ctkownika: 001",
            "confirmed_sending_date_warehouse": null,
            "confirmed_pickup_date_warehouse": null,
            "initial_delivery_date_warehouse": null,
            "data_verified_by_allegro_api": 0,
            "allegro_payment_id": null,
            "preferred_invoice_date": null,
            "need_support": 0,
            "reminder_date": null,
            "proposed_cash_on_delivery": "20.00",
            "invoice_bilans": null,
            "is_buying_admin_side": 0,
            "preliminary_buying_document_number": null,
            "buying_document_number": null,
            "packages_values": "{\"DPDd\": 0, \"GLSkd\": 0, \"GLSks\": 0}",
            "is_hidden": 0,
            "send_auto_messages": 1,
            "customer": {
              "id": 56326,
              "id_from_old_db": null,
              "login": "matikinus@gmail.com",
              "nick_allegro": null,
              "status": "ACTIVE",
              "is_staff": 0,
              "created_at": "2023-09-29T13:29:56.000000Z",
              "updated_at": "2023-09-29T13:29:56.000000Z",
              "login_token": null,
              "login_token_expires_at": null,
              "addresses": [
                {
                  "id": 87662,
                  "customer_id": 56326,
                  "type": "STANDARD_ADDRESS",
                  "firstname": null,
                  "lastname": null,
                  "firmname": null,
                  "nip": null,
                  "phone": "602426049",
                  "address": null,
                  "flat_number": null,
                  "city": "Rybnik",
                  "postal_code": "44-207",
                  "email": "matikinus@gmail.com",
                  "created_at": "2023-09-29T13:30:15.000000Z",
                  "updated_at": "2023-09-29T13:30:15.000000Z",
                  "country_id": null
                },
                {
                  "id": 87663,
                  "customer_id": 56326,
                  "type": "DELIVERY_ADDRESS",
                  "firstname": null,
                  "lastname": null,
                  "firmname": null,
                  "nip": null,
                  "phone": "602426049",
                  "address": null,
                  "flat_number": null,
                  "city": "Rybnik",
                  "postal_code": "44-207",
                  "email": "matikinus@gmail.com",
                  "created_at": "2023-09-29T13:30:15.000000Z",
                  "updated_at": "2023-09-29T13:30:15.000000Z",
                  "country_id": null
                }
              ]
            },
            "items": [
              {
                "id": 248909,
                "order_id": 85020,
                "product_id": 112019,
                "price": "0.00",
                "quantity": 135,
                "created_at": "2024-02-02T11:28:39.000000Z",
                "updated_at": "2024-02-02T11:28:39.000000Z",
                "net_purchase_price_commercial_unit": "47.10",
                "net_purchase_price_basic_unit": "157.0000",
                "net_purchase_price_calculated_unit": "31.4000",
                "net_purchase_price_aggregate_unit": "0.0000",
                "net_purchase_price_the_largest_unit": "0.0000",
                "net_selling_price_commercial_unit": "46.16",
                "net_selling_price_basic_unit": "153.8600",
                "net_selling_price_calculated_unit": "30.7700",
                "net_selling_price_aggregate_unit": "46.1600",
                "net_selling_price_the_largest_unit": "46.1600",
                "net_purchase_price_commercial_unit_after_discounts": "46.16",
                "net_purchase_price_basic_unit_after_discounts": "153.86",
                "net_purchase_price_calculated_unit_after_discounts": "30.77",
                "net_purchase_price_aggregate_unit_after_discounts": "46.16",
                "net_purchase_price_the_largest_unit_after_discounts": "46.16",
                "gross_selling_price_commercial_unit": "56.78",
                "gross_selling_price_basic_unit": "189.25",
                "gross_selling_price_calculated_unit": "37.85",
                "gross_selling_price_aggregate_unit": "56.77",
                "gross_selling_price_the_largest_unit": "56.77",
                "product_stock_packet_id": null,
                "product": {
                  "id": 112019,
                  "parent_id": 112004,
                  "category_id": 108,
                  "symbol": "B038F200",
                  "name": "besser fasada038 200mm",
                  "multiplier_of_the_number_of_pieces": null,
                  "url": "D:\\z\\styropak_fasada_042_1.jpg",
                  "weight_trade_unit": 0,
                  "weight_collective_unit": 0,
                  "weight_biggest_unit": 0,
                  "weight_base_unit": 0,
                  "description": "",
                  "video_url": "",
                  "manufacturer_url": "",
                  "priority": 15,
                  "meta_price": "p",
                  "meta_description": "",
                  "meta_keywords": "",
                  "status": "",
                  "description_photo_promoted": "",
                  "description_photo_table": "",
                  "description_photo_contact": "",
                  "description_photo_details": "",
                  "set_rule": "",
                  "manufacturer": "BESSER-TRZEBINIA",
                  "additional_info1": "038",
                  "additional_info2": "",
                  "supplier_product_name": "",
                  "product_name_on_collective_box": "",
                  "product_name_supplier": "BESSER-TRZEBINIA",
                  "product_name_supplier_on_documents": "BESSER-TRZEBINIA",
                  "supplier_product_symbol": "",
                  "product_name_manufacturer": "",
                  "symbol_name_manufacturer": "",
                  "pricelist_name": "",
                  "calculator_type": "",
                  "product_url": null,
                  "product_group": "|styropian fasada 038 200mm|",
                  "url_for_website": "\/storage\/products\/arsanit_fasada_040_1.jpg",
                  "created_at": "2023-02-07T17:44:46.000000Z",
                  "updated_at": "2024-02-05T13:48:25.000000Z",
                  "date_of_price_change": null,
                  "date_of_the_new_prices": null,
                  "product_group_for_change_price": "",
                  "products_related_to_the_automatic_price_change": "B038F",
                  "text_price_change": "",
                  "text_price_change_data_first": "",
                  "text_price_change_data_second": "",
                  "text_price_change_data_third": "",
                  "text_price_change_data_fourth": "",
                  "subject_to_price_change": 1,
                  "value_of_price_change_data_first": "157",
                  "value_of_price_change_data_second": "5",
                  "value_of_price_change_data_third": "0",
                  "value_of_price_change_data_fourth": "0",
                  "pattern_to_set_the_price": "[125]",
                  "variation_unit": "UB",
                  "variation_group": "styropiany",
                  "review": "",
                  "quality": "",
                  "quality_to_price": "",
                  "comments": "",
                  "value_of_the_order_for_free_transport": "",
                  "show_on_page": 0,
                  "token_prod_cat": null,
                  "trade_group_name": "",
                  "deleted_at": null,
                  "displayed_group_name": null,
                  "producent_override": "BESSER-TRZEBINIA",
                  "stock_product": null,
                  "average_amount_of_product_in_package": 0,
                  "employees_ids": "[115]",
                  "is_package": 0,
                  "save_name": 1,
                  "save_image": "1",
                  "assortment_quantity": "",
                  "delivery_type": "do wyceny",
                  "low_order_quantity_alert_text": "",
                  "layers_in_package": "",
                  "automatic_email_messages_14_column": "",
                  "automatic_email_messages_15_column": ""
                }
              },
              {
                "id": 248910,
                "order_id": 85020,
                "product_id": 112225,
                "price": "0.00",
                "quantity": 31,
                "created_at": "2024-02-02T11:28:40.000000Z",
                "updated_at": "2024-02-02T11:28:40.000000Z",
                "net_purchase_price_commercial_unit": "58.80",
                "net_purchase_price_basic_unit": "196.0000",
                "net_purchase_price_calculated_unit": "9.8000",
                "net_purchase_price_aggregate_unit": "0.0000",
                "net_purchase_price_the_largest_unit": "0.0000",
                "net_selling_price_commercial_unit": "57.62",
                "net_selling_price_basic_unit": "192.0800",
                "net_selling_price_calculated_unit": "9.6000",
                "net_selling_price_aggregate_unit": "57.6200",
                "net_selling_price_the_largest_unit": "57.6200",
                "net_purchase_price_commercial_unit_after_discounts": "57.62",
                "net_purchase_price_basic_unit_after_discounts": "192.08",
                "net_purchase_price_calculated_unit_after_discounts": "9.60",
                "net_purchase_price_aggregate_unit_after_discounts": "57.62",
                "net_purchase_price_the_largest_unit_after_discounts": "57.62",
                "gross_selling_price_commercial_unit": "70.87",
                "gross_selling_price_basic_unit": "236.26",
                "gross_selling_price_calculated_unit": "11.81",
                "gross_selling_price_aggregate_unit": "70.88",
                "gross_selling_price_the_largest_unit": "70.88",
                "product_stock_packet_id": null,
                "product": {
                  "id": 112225,
                  "parent_id": 112220,
                  "category_id": 54,
                  "symbol": "BE10036DP50",
                  "name": "besser EPS100 036 50mm",
                  "multiplier_of_the_number_of_pieces": null,
                  "url": "D:\\z\\styropak_fasada_042_1.jpg",
                  "weight_trade_unit": 0,
                  "weight_collective_unit": 0,
                  "weight_biggest_unit": 0,
                  "weight_base_unit": 0,
                  "description": "",
                  "video_url": "",
                  "manufacturer_url": "",
                  "priority": 5,
                  "meta_price": "p",
                  "meta_description": "",
                  "meta_keywords": "",
                  "status": "",
                  "description_photo_promoted": "",
                  "description_photo_table": "",
                  "description_photo_contact": "",
                  "description_photo_details": "",
                  "set_rule": "",
                  "manufacturer": "BESSER-TRZEBINIA",
                  "additional_info1": "036",
                  "additional_info2": "",
                  "supplier_product_name": "",
                  "product_name_on_collective_box": "",
                  "product_name_supplier": "BESSER-TRZEBINIA",
                  "product_name_supplier_on_documents": "BESSER-TRZEBINIA",
                  "supplier_product_symbol": "",
                  "product_name_manufacturer": "",
                  "symbol_name_manufacturer": "",
                  "pricelist_name": "",
                  "calculator_type": "",
                  "product_url": null,
                  "product_group": "|styropian EPS100 50mm|",
                  "url_for_website": "\/storage\/products\/arsanit_dach_podloga_EPS80_1.jpg",
                  "created_at": "2023-02-07T17:44:54.000000Z",
                  "updated_at": "2024-02-05T13:48:49.000000Z",
                  "date_of_price_change": null,
                  "date_of_the_new_prices": null,
                  "product_group_for_change_price": "",
                  "products_related_to_the_automatic_price_change": "BE10036DP",
                  "text_price_change": "",
                  "text_price_change_data_first": "",
                  "text_price_change_data_second": "",
                  "text_price_change_data_third": "",
                  "text_price_change_data_fourth": "",
                  "subject_to_price_change": 1,
                  "value_of_price_change_data_first": "196",
                  "value_of_price_change_data_second": "5",
                  "value_of_price_change_data_third": "0",
                  "value_of_price_change_data_fourth": "0",
                  "pattern_to_set_the_price": "[125]",
                  "variation_unit": "UB",
                  "variation_group": "styropiany",
                  "review": "",
                  "quality": "",
                  "quality_to_price": "",
                  "comments": "",
                  "value_of_the_order_for_free_transport": "",
                  "show_on_page": 0,
                  "token_prod_cat": null,
                  "trade_group_name": "",
                  "deleted_at": null,
                  "displayed_group_name": null,
                  "producent_override": "BESSER-TRZEBINIA",
                  "stock_product": null,
                  "average_amount_of_product_in_package": 0,
                  "employees_ids": "[115]",
                  "is_package": 0,
                  "save_name": 1,
                  "save_image": "1",
                  "assortment_quantity": "",
                  "delivery_type": "do wyceny",
                  "low_order_quantity_alert_text": "",
                  "layers_in_package": "",
                  "automatic_email_messages_14_column": "",
                  "automatic_email_messages_15_column": ""
                }
              },
              {
                "id": 248911,
                "order_id": 85020,
                "product_id": 112229,
                "price": "0.00",
                "quantity": 62,
                "created_at": "2024-02-02T11:28:40.000000Z",
                "updated_at": "2024-02-02T11:28:40.000000Z",
                "net_purchase_price_commercial_unit": "58.80",
                "net_purchase_price_basic_unit": "196.0000",
                "net_purchase_price_calculated_unit": "19.6000",
                "net_purchase_price_aggregate_unit": "0.0000",
                "net_purchase_price_the_largest_unit": "0.0000",
                "net_selling_price_commercial_unit": "57.62",
                "net_selling_price_basic_unit": "192.0800",
                "net_selling_price_calculated_unit": "19.2100",
                "net_selling_price_aggregate_unit": "57.6200",
                "net_selling_price_the_largest_unit": "57.6200",
                "net_purchase_price_commercial_unit_after_discounts": "57.62",
                "net_purchase_price_basic_unit_after_discounts": "192.08",
                "net_purchase_price_calculated_unit_after_discounts": "19.21",
                "net_purchase_price_aggregate_unit_after_discounts": "57.62",
                "net_purchase_price_the_largest_unit_after_discounts": "57.62",
                "gross_selling_price_commercial_unit": "70.87",
                "gross_selling_price_basic_unit": "236.26",
                "gross_selling_price_calculated_unit": "23.63",
                "gross_selling_price_aggregate_unit": "70.88",
                "gross_selling_price_the_largest_unit": "70.88",
                "product_stock_packet_id": null,
                "product": {
                  "id": 112229,
                  "parent_id": 112220,
                  "category_id": 54,
                  "symbol": "BE10036DP100",
                  "name": "besser EPS100 036 100mm",
                  "multiplier_of_the_number_of_pieces": null,
                  "url": "D:\\z\\styropak_fasada_042_1.jpg",
                  "weight_trade_unit": 0,
                  "weight_collective_unit": 0,
                  "weight_biggest_unit": 0,
                  "weight_base_unit": 0,
                  "description": "",
                  "video_url": "",
                  "manufacturer_url": "",
                  "priority": 9,
                  "meta_price": "p",
                  "meta_description": "",
                  "meta_keywords": "",
                  "status": "",
                  "description_photo_promoted": "",
                  "description_photo_table": "",
                  "description_photo_contact": "",
                  "description_photo_details": "",
                  "set_rule": "",
                  "manufacturer": "BESSER-TRZEBINIA",
                  "additional_info1": "036",
                  "additional_info2": "",
                  "supplier_product_name": "",
                  "product_name_on_collective_box": "",
                  "product_name_supplier": "BESSER-TRZEBINIA",
                  "product_name_supplier_on_documents": "BESSER-TRZEBINIA",
                  "supplier_product_symbol": "",
                  "product_name_manufacturer": "",
                  "symbol_name_manufacturer": "",
                  "pricelist_name": "",
                  "calculator_type": "",
                  "product_url": null,
                  "product_group": "|styropian EPS100 100mm|",
                  "url_for_website": "\/storage\/products\/arsanit_dach_podloga_EPS80_1.jpg",
                  "created_at": "2023-02-07T17:44:54.000000Z",
                  "updated_at": "2024-02-05T13:48:50.000000Z",
                  "date_of_price_change": null,
                  "date_of_the_new_prices": null,
                  "product_group_for_change_price": "",
                  "products_related_to_the_automatic_price_change": "BE10036DP",
                  "text_price_change": "",
                  "text_price_change_data_first": "",
                  "text_price_change_data_second": "",
                  "text_price_change_data_third": "",
                  "text_price_change_data_fourth": "",
                  "subject_to_price_change": 1,
                  "value_of_price_change_data_first": "196",
                  "value_of_price_change_data_second": "5",
                  "value_of_price_change_data_third": "0",
                  "value_of_price_change_data_fourth": "0",
                  "pattern_to_set_the_price": "[125]",
                  "variation_unit": "UB",
                  "variation_group": "styropiany",
                  "review": "",
                  "quality": "",
                  "quality_to_price": "",
                  "comments": "",
                  "value_of_the_order_for_free_transport": "",
                  "show_on_page": 0,
                  "token_prod_cat": null,
                  "trade_group_name": "",
                  "deleted_at": null,
                  "displayed_group_name": null,
                  "producent_override": "BESSER-TRZEBINIA",
                  "stock_product": null,
                  "average_amount_of_product_in_package": 0,
                  "employees_ids": "[115]",
                  "is_package": 0,
                  "save_name": 1,
                  "save_image": "1",
                  "assortment_quantity": "",
                  "delivery_type": "do wyceny",
                  "low_order_quantity_alert_text": "",
                  "layers_in_package": "",
                  "automatic_email_messages_14_column": "",
                  "automatic_email_messages_15_column": ""
                }
              }
            ]
          }
        }
      }
  ]

  auctions.value.forEach((auction: any) => {
    auction.offersExpanded = false;
    auction.activeOffers = auction.offers.splice(0, 3);
  });
};

const expandOffers = (auction: any) => {
  auction.offersExpanded = true;
  auction.activeOffers = auction.offers;
};

const collapseOffers = (auction: any) => {
  auction.offersExpanded = false;
  auction.activeOffers = auction.offers.splice(0, 3);
};

const showOfferTable = (auction: any) => {
  auction.offerTableShown = true;
};
</script>

<template>
  <div v-for="auction in auctions" class="border mx-auto w-1/2 p-3 mt-12 text-lg">
    <div class=" flex justify-between">
      <div>
        Numer przetargu: {{ auction.id }}
        <br>Koniec przetargu {{ auction.end_of_auction }}
        <br>Wstępna data dostawy wskazana przez klienta {{ auction.date_of_delivery }}
        <br>Procentowy udział ceny {{ auction.price }}
        <br>Procentowy udział jakości {{ auction.quality }}
        <br>Data rozpoczęcia przetargu {{ auction.created_at }}
        <br>Zaktualizowana {{ auction.updated_at }}
        <br>Email klienta: {{ auction.chat.order.customer.login }}
        <br>Telefon klienta: {{ auction.chat.order.customer.addresses[0].phone }} <a :href="`tel:${auction.chat.order.customer.addresses[0].phone}`">Zadzwoń</a>
      </div>

      <div>
        <a :href="auction.editPricesLink" target="__blank">
          <SubmitButton>
            Zmień swoje ceny w tym przetargu
          </SubmitButton>
        </a>

        <br>

        Oferty:
        <div v-for="offer in auction.activeOffers" class="tooltip">
            ID: {{ offer.id }} Firma: {{ offer.firm.symbol }} Cena: {{ offer.basic_price_net }}
            <span class="tooltip-text">
              Cena za opakowanie handlowe: {{ offer.commercial_price_net }}<br>
              Cena za m3: {{ offer.basic_price_net }}<br>
              cena za m2: {{ offer.calculated_price_net }}<br>
            </span>
        </div>

        <SubmitButton @click="auction.offersExpanded === false ? expandOffers(auction) : collapseOffers(auction)">
          <span v-if="auction.offersExpanded === false">
            Wyświetl wszystkie oferty
          </span>
          <span v-else>
            Ogranicz oferty
          </span>
        </SubmitButton>

        <button @click="showOfferTable(auction)" class="bg-green-500 mt-4 block px-4 py-2 rounded text-sm">
          Zobacz tabelę ofert
        </button>
      </div>
    </div>

    <div v-if="auction.offerTableShown" class="mt-4">
      <table>
        <tr>
          <th>Produkt</th>
          <th>Ilość</th>
          <th>Twoja cena</th>
          <th>Najniższa cena na ten moment</th>
        </tr>

        <tr v-for="item in auction.chat.order.items" class="mt-4">
          <td>{{ item.product.name }}</td>
          <td>{{ item.quantity }}</td>
          <td>
            {{
               auction.offers.filter((offer) => offer.firm_id === currentFirm.id).sort((a, b) => a.basic_price_net - b.basic_price_net)[0]?.basic_price_net
            }}
          </td>
          <td>{{ auction.offers.filter((offer) => offer.order_item_id === item.id).sort((a, b) => a.basic_price_net - b.basic_price_net)[0].basic_price_net }}</td>
        </tr>
      </table>

      <span>
        <SubmitButton>
          Zmień swoje ceny w tej ofercie
        </SubmitButton>
      </span>
    </div>
  </div>
</template>

<style scoped>
.tooltip {
  position: relative;
}

.tooltip .tooltip-text {
  visibility: hidden;
  background-color: black;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 20px;
  /* Position the tooltip */
  position: absolute;
  z-index: 1;
  bottom: 100%;
  left: 50%;
  margin-left: -60px;
}

.tooltip:hover .tooltip-text {
  visibility: visible;
}

</style>
